spring:
  profiles:
    active: dev
  application:
    name: springboot-learn
  jackson:
    # 蛇形命名法
    property-naming-strategy: SNAKE_CASE
    # 时间戳
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true

server:
  port: 8081

coisini:
  api-package: com.coisini.curtain.controller
  year-codes: A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z

wechat:
  appid: wx773b260ad2ca5502
  appsecret: 1e5236d847b7ee496d95751c0f25377e
  code2session: https://api.weixin.qq.com/sns/jscode2session?appid={0}&secret={1}&js_code={2}&grant_type=authorization_code

system:
  condition: linux
