#生产环境配置

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/curtain?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8
    username: root
    password: sunday

# 开启权限拦截
auth:
  enabled: true

# 开启请求日志记录
request-log:
  enabled: true



